### ISSUE TITLE
[home] update 3rd illustration 

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#102]
- update copy to match copydoc
- move home directory in to host system

(I forwarded the source files to you via email Karl)

**Comment by kwm14** [comment]
@barrymcgee please find DropBox link to updated illustrations. All three need to be updated not just the 3rd illustration.

Thanks

https://www.dropbox.com/sh/fzla4bienktgq2p/AACb5PNhzWnUUsssZKaw6A_Sa?dl=0

**Comment by barrymcgee** [comment]
Fixed in #105
