### ISSUE TITLE
[home] Popular snaps row

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#104]
- look at the copy, not over two lines, make it a caption for visual
- icons stronger

we want to celebrate the twelve best snaps, if we have more we want to update this to make them match the best snaps.

**Comment by kwm14** [comment]
@barrymcgee new styling applied to 'Popular snaps' table. 3 x 4 and we can then increase the size of icons. As they're SVG we can adjust during build :)
