### ISSUE TITLE
[navigation] add hover and selected states

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#106]
please add a hover and selected state to the navigation.

**Comment by kwm14** [comment]
rollover state colour #F7F7F7

selected state colour #E95420 and styling allah maas.io with a 3px keyline at the base (attached image for reference) 

**Selected state**
![snapcraft io-desktop-selected-state](https://cloud.githubusercontent.com/assets/17748020/16911615/cf8d11fa-4cdf-11e6-8e0a-cbc23924c5e9.png)

**Comment by barrymcgee** [comment]
Addressed by #113
