### ISSUE TITLE
Change any links to https://snapcraft.io to link to http://snapcraft.io instead

### ISSUE THREAD

**Issue by nskaggs** [ubuntudesign/snapcraft.io#111]
HTTPS links to https://snapcraft.io/* timeout trying to load. This breaks things like that tour which specifies hitting https://snapcraft.io/create/#begin, etc.

**Comment by nottrobin** [comment]
Thanks @nskaggs. Yes, HTTPS is not currently supported on snapcraft.io. Which tour are you referring to? We should make sure any links to https://snapcraft.io are updated to link to http://snapcraft.io instead.

**Comment by nottrobin** [comment]
Ah found it - you mean [here](https://github.com/ubuntudesign/snapcraft.io/blob/master/create/index.html#L44)? Yes we should definitely update that. Thanks for bringing it to our attention.

**Comment by nskaggs** [comment]
@nottrobin yep, that's the place. Not sure if it was elsewhere, and https links didn't work, hence the original title.

**Comment by nottrobin** [comment]
I've submitted [this pull request](https://github.com/snapcore/snapcraft/pull/665) to the snapcraft project to update these links.

**Comment by barrymcgee** [comment]
Addressed by #113

**Comment by elopio** [comment]
Can we have another bug to support https in snapcraft.io in the future?

**Comment by barrymcgee** [comment]
Good idea @elopio - I've now added this as issue #115.

**Comment by elopio** [comment]
ty.
