### ISSUE TITLE
#begin anchor tag doesn't exist on create/#begin

### ISSUE THREAD

**Issue by nskaggs** [ubuntudesign/snapcraft.io#112]
Snapcraft references https://snapcraft.io/create/#begin, but there is no begin anchor tag on the page.

**Comment by nskaggs** [comment]
The fix for this maybe to change snapcraft itself (as well as the tour), to no longer include the anchor tag. Let me know, and I'll open an issue against snapcraft as well.

**Comment by nottrobin** [comment]
Thanks. I think the `tour` anchor makes sense, and does exist. We'll change it to that.

**Comment by nottrobin** [comment]
I've submitted [this pull request](https://github.com/snapcore/snapcraft/pull/665) to the snapcraft project to update these links.

**Comment by barrymcgee** [comment]
Resolved by #117
