### ISSUE TITLE
[docs] footer looks dodgy on short pages

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#130]
![screen shot 2016-07-19 at 15 12 15](https://cloud.githubusercontent.com/assets/7945048/16951005/5b4abc68-4dc3-11e6-8ec7-9486deee7ca7.png)

**Comment by pmahnke** [comment]
perhaps a min-height on the content area?

**Comment by nottrobin** [comment]
Related to https://github.com/ubuntudesign/snapcraft.io/issues/127 ?
