### ISSUE TITLE
No bold text within code snippets on firefox

### ISSUE THREAD

**Issue by Idealcoder** [ubuntudesign/snapcraft.io#151]
## Context

When using firefox, there is no bold text within code snippets

## Process

1. Visit snapcraft.io on firefox
2. Click on create
3. Scroll down to "metadata: snap.yaml defines the properties of a snap"
4. "amd64" is not highlighted in bold

## Current result

On firefox (incorrect):
![screenshot-firefox-boldmissing](https://cloud.githubusercontent.com/assets/3229532/17139700/7a10fdfe-533d-11e6-8882-55db507c4141.png)

## Expected result 
On chromium:
![screenshot-chromium](https://cloud.githubusercontent.com/assets/3229532/17139701/7a13095a-533d-11e6-83c1-99e9cd882073.png)

**Comment by barrymcgee** [comment]
This has been resolved.

https://www.dropbox.com/s/c5ct5hg1jxud58y/Screenshot%202016-08-23%2015.41.16.png?dl=0
