### ISSUE TITLE
Code blocks need margin bottom in small screen

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/snapcraft.io#154]
## Context

Where there are code blocks (homepage, create) in small screen (eg. iPhone 6) the code blocks have margin bottom. 

## Expected result

Margin top should be at least same as margin top.

**Comment by caldav** [comment]
I was about to report this, yes, here is an example of a page where this is a bit critical and brings confusion: 

![screenshot from 2016-07-26 15-59-52](https://cloud.githubusercontent.com/assets/18480003/17141148/5e1a2608-534b-11e6-9417-de048181254d.png)

![screenshot from 2016-07-26 16-00-19](https://cloud.githubusercontent.com/assets/18480003/17141157/6747300e-534b-11e6-8470-d97491cd3f90.png)

**Comment by anthonydillon** [comment]
This seems like a vanilla issue.
