### ISSUE TITLE
The ARM logo on the homepage is the wrong colour

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/snapcraft.io#161]
Its currently #00E4F1 but should be #128CAB. It is also inside a single image which makes it difficult to update individually . The single SVG of all three logos contains a single SVG and a base64 of the other two. We should use SVGs inside SVGs,

**Comment by kwm14** [comment]
@anthonydillon I was having issues with colouration of logos when on the sprint, in Chrome it's lighter but in Safari the colour is correct. Odd!

Also when @barrymcgee was building the page he requested for it to be one single SVG rather than three individual SVG logos.

**Comment by nottrobin** [comment]
Wasn't this fixed already by #162?

**Comment by anthonydillon** [comment]
Yes, I fixed this after filling the issue. All logos are separate and added a few new ones.
