### ISSUE TITLE
Snapcraft documentation points at unsupported store API documentation

### ISSUE THREAD

**Issue by evandandrea** [ubuntudesign/snapcraft.io#167]
http://snapcraft.io/docs/core/store has the following text, "Snaps are not tied to a specific type of store and you can host them any way you want. Although, to integrate with the snap command (beyond the install/remove commands), the server needs to be based on the Store API specs."

The "Store API specs" text links off to https://wiki.ubuntu.com/AppStore/Interfaces/ClickPackageIndex. This is not supported API documentation. If anywhere, this link should point to https://myapps.developer.ubuntu.com/docs/api/snap.html. However, I'll let @noise speak to how ready we are to share that.

**Comment by caldav** [comment]
Interesting, what about the search endpoint? This doesn't seem to be documented in https://myapps.developer.ubuntu.com/docs/api/snap.html. Is that http://search.apps.ubuntu.com/docs/?

**Comment by evandandrea** [comment]
@caldav correct, http://search.apps.ubuntu.com/docs/. Again, I'm not sure whether we want to publicise either of those yet given we haven't made a statement one way or another on API stability.

**Comment by noise** [comment]
http://search.apps.ubuntu.com/docs/ is the current/proper docs, but I'd prefer we not advertise it this time.

**Comment by caldav** [comment]
Ok, in this case, I think the best would be to drop the API link for now, and simply let people figure it out from the custom store example.

@noise, do you have a rough ETA on when this API doc will be ready for public consumption?

**Comment by caldav** [comment]
@noise any news on this?

**Comment by noise** [comment]
@caldav no ETA currently. We still have a lot of things in flux.

**Comment by caldav** [comment]
Fixed in docs trunk.
