### ISSUE TITLE
Sections of main page are not linkable

### ISSUE THREAD

**Issue by mikemccracken** [ubuntudesign/snapcraft.io#177]
## Context

It'd be nice if there were some anchors for each of the section headers, like "Snaps are read-only and have segregated data stores", so we could link directly to them.

**Comment by anthonydillon** [comment]
Thank you very much @mikemccracken, this issue will be run by design and addressed shortly.

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Nt30ghub&#x2F;1653-add-id-anchor-links-to-homepage"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> add id anchor links to homepage</a>

**Comment by pmahnke** [comment]
this is live now

h1 id="snapcraft_home_banner"
section id="snapcraft_home_install"
section id="snapcraft_home_how-snaps-work"
div id="snapcraft_home_how-snaps-work_read-only"
div id="snapcraft_home_how-snaps-work_integration"
div id="snapcraft_home_how-snaps-work_architecture"
section id="snapcraft_home_using-snaps"
div id="snapcraft_home_using-snaps_fresh"
div id="snapcraft_home_using-snaps_revert"
div id="snapcraft_home_using-snaps_channels"
section id="snapcraft_home_featured-snaps"
section id="snapcraft_home_get-crafting"
