### ISSUE TITLE
Need to clarify use cases for SNAP_DATA vs. SNAP_USER_DATA

### ISSUE THREAD

**Issue by mikemccracken** [ubuntudesign/snapcraft.io#178]
The section titled "Snaps are read-only and have segregated data stores" doesn't clearly state when a program would use `$SNAP_DATA` vs `$SNAP_USER_DATA`.

The gist is that a command installed by a snap which will run as the user should write to `$SNAP_USER_DATA` because it has the same permissions as the user who will run it, and thus won't be able to write to `$SNAP_DATA`. Presumably, `$SNAP_DATA` would be used by daemons installed by the snap.

**Comment by barrymcgee** [comment]
@caldav Can you confirm the copy change to be made here?

**Comment by caldav** [comment]
Fixed with a new reference page in docs. http://snapcraft.io/docs/reference/env
