### ISSUE TITLE
typo in imported docs

### ISSUE THREAD

**Issue by mikemccracken** [ubuntudesign/snapcraft.io#179]
This page has a typo:

http://snapcraft.io/docs/core/interfaces

the word 'manual' is misspelled at the end of this sentence:
"In addition, future enhancements may provide for the gadget snap to connect snaps to interfaces – so that preinstalled snaps get their interfaces without the need for a manaul connection."

I wanted to just send a pull request with a fix, but the docs are imported from a repository that I can't access.

**Comment by nottrobin** [comment]
Ah that's a good point. Surely there's no reason for [snappy-docs](https://github.com/canonicalltd/snappy-docs) to be private is there? @caldav, do you know if it would be okay to make it public?

**Comment by caldav** [comment]
I don't see why not! Not sure if I have a switch for this on my end, though (afaics, nothing in the UI allows me to manage the repo)

**Comment by caldav** [comment]
The typo is fixed in the doc repo.
