### ISSUE TITLE
No mention that devmode snaps will not appear in snap find

### ISSUE THREAD

**Issue by evandandrea** [ubuntudesign/snapcraft.io#18]
http://snapcraft.io/create does not mention that when you publish your snap in devmode, it will not appear in search results. The reader can find and install their snap by running `snap install hello --devmode`

**Comment by pmahnke** [comment]
Ev

Can you update the copy doc and add a comment for me where you would like the change?

Thanks,

Peter

**Comment by anthonydillon** [comment]
@evandandrea Would you mind updating the copy doc with the changes you require. If you do not have the doc to hand please ping me and I'll share it.
