### ISSUE TITLE
Users without xenial-updates/universe can't get snapcraft version 2.11 tour

### ISSUE THREAD

**Issue by elopio** [ubuntudesign/snapcraft.io#180]
Might be worth noting what apt sources need to be enabled to get snapcraft 2.11 as mentioned in the docs.
http://snapcraft.io/create/

Without enabling xenial-updates/universe, I was unable to install snapcraft > 2.8.4.

(Moved from https://bugs.launchpad.net/snappy/+bug/1611083)

**Comment by caldav** [comment]
Nice catch.

**Comment by elopio** [comment]
thank you!
