### ISSUE TITLE
Add OpenWrt to the list of supported distributions

### ISSUE THREAD

**Issue by caldav** [ubuntudesign/snapcraft.io#183]
## Context

OpenWrt needs to be added to the homepage as a supported distro.

### Relevant links

* [OpenWrt logo](https://commons.wikimedia.org/wiki/File:Openwrt_Logo.svg) 
* [Change in /docs/install](https://github.com/CanonicalLtd/snappy-docs/blob/new-structure/core/install.md)
* https://openwrt.org/

**Comment by caldav** [comment]
@pmahnke do you know who could take this design work item? We are waiting on it to do the announce.

**Comment by pmahnke** [comment]
@caldav is this just a matter of adding the logo?

**Comment by caldav** [comment]
Yes, that's pretty much it, thanks!
