### ISSUE TITLE
Unable to import documentation

### ISSUE THREAD

**Issue by justincan** [ubuntudesign/snapcraft.io#187]
## Summary

Unable to import the documentation as per the README.md

## Process

$ ./import-docs.sh
Cloning into 'docs'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by caldav** [comment]
The doc repo is private and it looks like you don't have access. Currently looking into making it public.

**Comment by nottrobin** [comment]
Thanks for bringing this up @justincan.

I've just made [canonicalltd/snappy-docs](https://github.com/CanonicalLtd/snappy-docs) public. I trust this will solve your issue, so I'm closing this issue. Please re-open if `./import-docs.sh` still fails for you.
