### ISSUE TITLE
Incorrect sentence on snapcraft tour

### ISSUE THREAD

**Issue by oSoMoN** [ubuntudesign/snapcraft.io#19]
I’m following the snapcraft tour at http://snapcraft.io/create/, and one sentence doesn’t sound right.

« build/ where the build is append »

(under the "02-parts: Snapcraft makes snaps out of parts" section)

That should probably be: « build/ where the builds happens »

**Comment by keshavbhatt** [comment]
agree "bull"

**Comment by elopio** [comment]
Fixed in #20.

**Comment by pmahnke** [comment]
thanks for reporting, yes this was fixed.
