### ISSUE TITLE
Change --force-dangerous to --dangerous

### ISSUE THREAD

**Issue by caldav** [ubuntudesign/snapcraft.io#198]
## Summary

--force-dangerous needs to be changed to --dangerous when the next version of snapd lands in xenial

**Comment by barrymcgee** [comment]
@caldav When is the next version of snapd expected to land in Xenial?

**Comment by caldav** [comment]
In the end --force-dangerous has been kept around for compatibility, no rush here, I'll push an update next week. Thanks for the reminder, though.
