### ISSUE TITLE
Gentoo install instructions

### ISSUE THREAD

**Issue by kefnab** [ubuntudesign/snapcraft.io#199]
## Summary

The current install directions do not work for Gentoo

## Process

The current instructions are not compatible with Gentoo's portage (package management), and there are some minor code problems in those referenced repositories.

## Fix

Redirect users to @zyga's [gentoo-snappy](https://github.com/zyga/gentoo-snappy) repository.  The readme.md provides instructions for adding it to the main `repos.conf` directory so that `snapd` and `snap-confine` can both be installed and managed with portage.

**Comment by caldav** [comment]
Thank a lot for the heads up!

Fixed by: https://github.com/CanonicalLtd/snappy-docs/commit/dadff18b51e86e47b0af0d00cedc34a8e765b56d
