### ISSUE TITLE
Visual design

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/snapcraft.io#2]
Visual design explorations of snappycraft.io

**Comment by kwm14** [comment]
First iteration of visuals based from Google Doc and conversations (17/5):

### v1
![snapcraft io-desktop-002](https://cloud.githubusercontent.com/assets/17748020/15380222/6c08e2b6-1d29-11e6-9a33-9035fc59d92c.png)

### v2
![snapcraft io-desktop-003](https://cloud.githubusercontent.com/assets/17748020/15380225/6c0d418a-1d29-11e6-8d3f-c412c7f655e8.png)

### v3
![snapcraft io-desktop-004](https://cloud.githubusercontent.com/assets/17748020/15380223/6c09f598-1d29-11e6-828b-1754a2d8fb1d.png)

### v4
![snapcraft io-desktop-005](https://cloud.githubusercontent.com/assets/17748020/15380224/6c0c38da-1d29-11e6-830e-0e76d20d6d44.png)

**Comment by kwm14** [comment]
Second iteration taking both Ale and Carla's feedback into account (18/5):

- Explore hero image and summary section
- Introduce new colours
- Chat with Marco about what the community want to see
- Explore new graphics rather than Snappy ident

### v5
![snapcraft io-desktop-005](https://cloud.githubusercontent.com/assets/17748020/15380276/0f869c76-1d2a-11e6-9f9a-aa75a0aa0c52.png)

### v6
![snapcraft io-desktop-006](https://cloud.githubusercontent.com/assets/17748020/15380275/0f858854-1d2a-11e6-9dee-efaaf802bb45.png)

### v7
![snapcraft io-desktop-009](https://cloud.githubusercontent.com/assets/17748020/15380317/626a039c-1d2a-11e6-8e01-8b301392bcdb.png)

### v8
![snapcraft io-desktop-008](https://cloud.githubusercontent.com/assets/17748020/15380278/0fb3949c-1d2a-11e6-90d8-6eb18c790a19.png)

**Comment by kwm14** [comment]
Showed new explorations to MS and his feedback is below (18/5):

- Try new graphic in hero image - squircle layout as seen in Ubuntu but with Snaps
- Add CentoS and Mint OS into linux section
- Add linux operating system logos into own row - colours logos on white
- Hero background colour to be light grey/suru wallpaper
- MS updating copy doc
- Command lines to be have light grey background
- Close row height on 'popular snaps' - it will grow when more Snaps developed so needs to cater
- Add call to action below snaps 'get started' or 'find out more'

**Comment by jamiedawsonyoung** [comment]
Looking good @kwm14 :-) has @yaili seen these? She might have some useful feedback too. Glad it's going well out there!

**Comment by yaili** [comment]
Hi,

I don't have much feedback, it's pretty good. Just remember to think about the small and medium screen views, and if there are any changes to agreed patterns — like code blocks — make sure that is documented somewhere.

**Comment by kwm14** [comment]
@jamiedawsonyoung @yaili thanks for your feedback.

@yaili is there a patter that we currently use for code blocks? Mark wants the styling to have a light background and text in #333 so it's legible for users to read.

**Comment by yaili** [comment]
Hi @kwm14 

This is what was agreed for Vanilla: https://github.com/ubuntudesign/vanilla-framework/issues/290#issuecomment-217154330

I believe the styles follow the ones in Juju. Hope this helps.

**Comment by kwm14** [comment]
Hi @yaili 

Thanks for sending across current Vanilla styling for code blocks. Both styles will work in the webpage so will explore both.

Thanks.

**Comment by kwm14** [comment]
New iteration taking Mark's feedback into account (20/5):

- New graphic and background updated in hero image
- CentoS and Suse (replaced MintOS) linux providers added.
- New row displaying linux OS logos
- MS updated 'command line' sections in copy doc
- Command line styling updated to Vanilla styles
- New layout on 'Popular snaps' section
- Call to action added in separate row

@carlaberkers @jamiedawsonyoung @yaili 

### v9
![snapcraft io-desktop-002](https://cloud.githubusercontent.com/assets/17748020/15439027/db05c2a0-1e83-11e6-8c24-cde3f2433940.png)

**Comment by kwm14** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RXEMd45Y&#x2F;241-snappy-snapcraft-io"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [Snappy] snapcraft.io</a>

**Comment by kwm14** [comment]
Feedback from visual stand up with team (24/5):

- Look at the Snapcraft logo
- Should the command line be dark
- Juju docs people wanted dark background
- Speak to Mark about why we use dark backgrounds (show both)
- Try dark background with syntax colour
- Be consistent with snap icons grid

**Comment by kwm14** [comment]
Updated design taking feedback into account:

- Added more snap icons in hero image
- Consistent 'squircle' icons in popular snaps section
- Explored commad line in black - case that Juju docs people wanted it this style

### v10
![snapcraft io-desktop-002](https://cloud.githubusercontent.com/assets/17748020/15509041/e697a05e-21c9-11e6-939d-44943d6a54cd.png)

**Comment by jamiedawsonyoung** [comment]
I like the dark look but I would try the syntax colouring on both a dark and a light look so we can maybe try and get the dark version back. I think it's a decent argument (harder to scan) that was presented by Spencer about the testing they did with the docs on Juju.

**Comment by anthonydillon** [comment]
@kwm14 Can this issue be closed now the site is live?

**Comment by kwm14** [comment]
@anthonydillon yes it can
