### ISSUE TITLE
snapcraft upload command is deprecated

### ISSUE THREAD

**Issue by murraybd** [ubuntudesign/snapcraft.io#200]
## Summary

Tour says to use snapcraft upload but it's deprecated, see http://snapcraft.io/create/ for instructions regarding upload command.

## Process

 $ snapcraft upload xyz
DEPRECATED: Use `push` instead of `upload`

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. One of the team will pick this up shortly.
