### ISSUE TITLE
The examples link on http://snapcraft.io/docs/reference/plugins/dump is broken.

### ISSUE THREAD

**Issue by nturner** [ubuntudesign/snapcraft.io#213]
## Summary

The examples link on http://snapcraft.io/docs/reference/plugins/dump is broken.

## Process

Go to http://snapcraft.io/docs/reference/plugins/dump and click on Examples

## Current and expected result

I'd expect some cool examples. Instead, I see an error page.

**Comment by nottrobin** [comment]
This issue was moved to CanonicalLtd/snappy-docs#18
