### ISSUE TITLE
Misuse of Apache Software Foundation trademark

### ISSUE THREAD

**Issue by zznate** [ubuntudesign/snapcraft.io#222]
Hi folks,
Sorry upfront for the mean title, but could you please update the "Cassandra" snap to read  "Apache Cassandra?"  

As it stands now, the usage of just "Cassandra" on the front page without any context outside of your product is a violation of our trademark. As per above, simply prepending "Apache " should suffice to fix this. 

That all said, we do very much appreciate you featuring Apache Cassandra on the front page and are interested to see how this approach plays out for our users. 

For future reference, specifics on ASF trademark policy can be found here:
http://www.apache.org/foundation/marks/
http://www.apache.org/foundation/marks/faq/#products

**Comment by caldav** [comment]
Fixing, thanks for the heads up and the links.

**Comment by zznate** [comment]
Awesome thanks for the quick turn around. And thanks again for featuring Cassandra on the front page!
