### ISSUE TITLE
Add NATS and ArangoDB to the featured snaps grid

### ISSUE THREAD

**Issue by caldav** [ubuntudesign/snapcraft.io#229]
Maybe in place of Freecad and Hangups.

**Comment by magdalena-mirowicz** [comment]
@joanasa89 please prepare assets for Barry

**Comment by caldav** [comment]
@joanasa89 
NATS: http://nats.io/ (only logo I've found is https://nats.io/img/large-logo.png)
ArangoDB: https://www.arangodb.com/logos/

**Comment by caldav** [comment]
NATS: found a better one https://pbs.twimg.com/profile_images/664519292629598208/hmyL7XUa_400x400.png

**Comment by evandandrea** [comment]
Provided by the kind folks at NATS.io to us:

![nats-color](https://cloud.githubusercontent.com/assets/1523179/20844093/cbe92d30-b883-11e6-981f-7bcaacc1669d.png)

**Comment by caldav** [comment]
@evandandrea do you think we can use the square icon I've linked to above? Because with this one, it's going to be unreadable.

**Comment by evandandrea** [comment]
@caldav probably. Can I ask you to reach out to Brian at NATS to make sure (email PMed)?

**Comment by caldav** [comment]
@evandandrea :+1: 
@joanasa89 got a confirmation that https://pbs.twimg.com/profile_images/664519292629598208/hmyL7XUa_400x400.png is ok to use

**Comment by joanasa89** [comment]
nats logo: 
svg - https://assets.ubuntu.com/v1/feef8ab1-nats.svg
png - https://assets.ubuntu.com/v1/653d49e6-nats.png

aragond: 
png - https://assets.ubuntu.com/v1/4e3909d0-arangod_logo.png
svg - https://assets.ubuntu.com/v1/6d9e1b6e-arangod_logo.svg

**Comment by joanasa89** [comment]
https://assets.ubuntu.com/v1/5eca4c49-arango_png.png
https://assets.ubuntu.com/v1/c9ded7dd-nats_png.png
