### ISSUE TITLE
20-PARTS-PLUGINS/01-reusable-part: missing g++ dependency 

### ISSUE THREAD

**Issue by lightonflux** [ubuntudesign/snapcraft.io#230]
## Process

 1. Spin up droplet on digital ocean with 16.04 (no idea if they use the standard server image)
 2. Follow the steps in the tour
 3. Run snapcraft in 20-PARTS-PLUGINS/01-reusable-part
 4. Get an error when running the part hello-world: No CMAKE_CXX_COMPILER could be found.
 5. Be confused why the tutorial does not work perfectly.
 6. Think about it and install `build-essentials` manually (`g++` should be enough) 

## Current and expected result

Current: Does not create snap.

Expected: Creates snap without manual intervention.

**Comment by caldav** [comment]
Opened on snapcraft itself as well: https://bugs.launchpad.net/snapcraft/+bug/1650087, as I believe there is two parts to it. The tutorial should ensure you have g++ installed, but snapcraft should probably do it too.
