### ISSUE TITLE
Site links to deprecated examples

### ISSUE THREAD

**Issue by lightonflux** [ubuntudesign/snapcraft.io#237]
## Summary

The snapcraft.io site links to examples that are deprecated.

## Process

Go to 

 * https://developer.ubuntu.com/en/snappy/support/faq/
   * Read **Examples** section and visit links
 * http://snapcraft.io/docs/build-snaps/
   * Scroll down and click **Browse snap examples ›**

### Current: 

Be surprised that officially recommended examples are DEPRECATED if you even find that mention. (The direct links to the github wiki are not in any way marked as deprecated, you have to visit the code tab).

### Expected: 

 LInk to recent and valid examples as explained [here](https://github.com/ubuntu/snappy-playpen#deprecated---the-snappy-playpen)

## Screenshot
![bildschirmfoto von 2016-12-15 15-40-54](https://cloud.githubusercontent.com/assets/1377943/21228147/00ddf2e2-c2dd-11e6-8a61-dd457fde8a3e.png)

**Comment by caldav** [comment]
Fixed by: https://github.com/CanonicalLtd/snappy-docs/commit/5c019a9f61c38db6298b2c1b4016d2f196dc82c2

**Comment by lightonflux** [comment]
Who do i need to bother to get the (locked?) wiki article updated?

→ https://developer.ubuntu.com/en/snappy/support/faq/

**Comment by caldav** [comment]
The faq page has been updated.

**Comment by lightonflux** [comment]
Found another occurrence:

http://snapcraft.io/community/

> Joining the growing community of Snappy developers is as simple as signing up to a mailing list or have some fun in the **Snappy Playpen.**
