### ISSUE TITLE
 prompting for your system password each time you run snapcraft is not true

### ISSUE THREAD

**Issue by liu-xiao-guo** [ubuntudesign/snapcraft.io#241]
Start by building this snap, noting that you’ll be prompted for your system password each time you run snapcraft:

$ snapcraft
[sudo] password for [your user name]:  ***
Preparing to pull gnu-hello
Pulling gnu-hello
Preparing to build gnu-hello
Building gnu-hello
...
Snapped hello_2.10_amd64.snap

If you do not use "sudo" in the snapcraft command, you will not be prompted for password.

**Comment by caldav** [comment]
It will prompt for a password if you use a plugin that requires deb dependencies or if you need stage or build packages. In this case, you are right, it doesn't require sudo, this needs rewording.

**Comment by caldav** [comment]
Fixed with https://github.com/CanonicalLtd/snappy-docs/commit/2c4484a8e3f58fdc0cf3ca3f0a31ba2123bd81f8
