### ISSUE TITLE
SNAP_COMMON_DATA is wrong

### ISSUE THREAD

**Issue by liu-xiao-guo** [ubuntudesign/snapcraft.io#242]
on the picture:

https://assets.ubuntu.com/v1/f070c416-Update-Snapcraft%28dot%29io-architecture.svg

SNAP_COMMON_DATA never exists, and it should be replaced by SNAP_DATA

**Comment by caldav** [comment]
@liu-xiao-guo I think you mean SNAP_DATA_COMMON and SNAP_COMMON (c.f [Environment variables](http://snapcraft.io/docs/reference/env)), and I agree, things have changed this the creation of the diagram, it should be updated.

@joanasa89 can you have a look? I see three issues with the current asset:

 * First row, 2nd box: "SNAP_DATA_COMMON" needs to be replace by "SNAP_COMMON"
 * First row, 2nd box: underscores shouldn't look duplicated
 * Third row, right: the quotation marks around 'home' are trying to escape

Thanks

**Comment by joanasa89** [comment]
I've made the previous changes.  @caldav can you please have a look and see if looks ok?
https://assets.ubuntu.com/v1/143dff64-Update-Snapcraft%28dot%29io-architecture_v2.svg

Thanks

**Comment by caldav** [comment]
Looks good to me!
