### ISSUE TITLE
“Docs” section has different header margin, and footer, than the rest of the site

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntudesign/snapcraft.io#267]
1. Go to http://snapcraft.io/
2. Go to any part of the site except “Docs”.
3. Go to “Docs”.

What happens:
- The header margins are different.
- The footer text is the same, but the font size is different.
- The footer is missing the social media buttons.

What should happen:
- The header margins should be the same.
- The footer font size should be the same.
- The footer should either have, or not have, the social media buttons consistently.

**Comment by nottrobin** [comment]
This will be resolved by moving the docs off the main site in #239.
