### ISSUE TITLE
Isnapd package on ubuntu 16.04 failed to install

### ISSUE THREAD

**Issue by gcclinux** [ubuntudesign/snapcraft.io#27]
Hello I am trying to install snapd  in my 64bit Ubuntu 16.04 laptop and I am having issue, i browsed around but can't see to fix it.

Here is the outcome when i try to install it.
........
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  snapd
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
1 not fully installed or removed.
Need to get 0 B/4,278 kB of archives.
After this operation, 22.1 MB of additional disk space will be used.
(Reading database ... 371751 files and directories currently installed.)
Preparing to unpack .../archives/snapd_2.0.8_amd64.deb ...
Unpacking snapd (2.0.8) ...
dpkg: error processing archive /var/cache/apt/archives/snapd_2.0.8_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/snap.1.gz', which is also in package snap 2013-11-29-1ubuntu2
Reinstalling /etc/ld.so.conf.d/snappy.conf that was moved away
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/snapd_2.0.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
$

Please advise what the fix is.

Many Thanks

**Comment by anthonydillon** [comment]
@gcclinux Thank you very much for reporting this issue to us. I have requested one of the Snappy developers to take a look.

**Comment by dholbach** [comment]
@gcclinux This is not the best place to discuss it, as this repo is all about the website. Can you maybe subscribe to https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1571989 which is the issue you're seeing? (If you don't need it, you could remove the `snap` package and run `sudo dpkg --configure -a`.)

**Comment by anthonydillon** [comment]
@dholbach thank you. Closing on this project,
