### ISSUE TITLE
Refer to snapcraft's social media channels

### ISSUE THREAD

**Issue by dholbach** [ubuntudesign/snapcraft.io#30]
We created social media channels for snapcraft and it'd be good to refer to them (maybe in the footer), so interested users can stay up to date on what's happening.

Namely this would be:

 - https://www.facebook.com/snapcraftio
 - https://twitter.com/snapcraftio
 - https://plus.google.com/+SnapcraftIo

**Comment by anthonydillon** [comment]
Thanks @dholbach, on it.
