### ISSUE TITLE
Write 'snap' and 'snapcraft' with Capital letters.

### ISSUE THREAD

**Issue by ktatar156** [ubuntudesign/snapcraft.io#38]
Hello,

Shouldn't we write 'snap' (and also 'snapcraft') word in websites (and everywhere else except command line) with capital letter - 'Snap'? It will help to tell do-not-translate that word. In example:

EN:
You can install snap package everywhere!
PL:
Możesz zainstalować paczkę snap wszędzie!

In my opinion, above looks ugly. And now:

EN:
You can install Snap package everywhere!
PL:
Możesz zainstalować paczkę Snap wszędzie!

Looks better. If it's written with lowercase, it suggests to translate word 'snap' somehow (and I don't know if there's any word in PL lang. for that).

**Comment by anthonydillon** [comment]
Thanks for spotting this. @pmahnke what do you think?
