### ISSUE TITLE
Typo on Snapcraft homepage

### ISSUE THREAD

**Issue by duke1995** [ubuntudesign/snapcraft.io#41]
On the Snapcraft homepage (http://snapcraft.io/), I see the following text: 

![2016-07-04_165207](https://cloud.githubusercontent.com/assets/4910210/16564433/bb3514f6-4207-11e6-9568-f45778dcb5da.png)

Note that you could have directly installed hello from the beta channel via:
$ snap install hello **--channel-beta**

I suppose this should be: 

Note that you could have directly installed hello from the beta channel via:
$ snap install hello **--channel=beta**

**Comment by jamiedbennett** [comment]
The final syntax will be

$snap install hello --beta

Which is not implemented yet.
