### ISSUE TITLE
favicon is still ubuntu logo

### ISSUE THREAD

**Issue by jamiedbennett** [ubuntudesign/snapcraft.io#42]
On Chrome/Firefox the favicon is still the ubuntu logo. This needs to be changed to the snapcraft icon.

**Comment by pmahnke** [comment]
there is no snapcraft icon and we were told to use the ubuntu logo... have you been told otherwise?

**Comment by jamiedbennett** [comment]
Yes, had a chat with Mark earlier. We should not have distro-specific branding unless it makes sense and on the favicon it does not. Can we create something from the unofficial snapcraft logo i.e. the building blocks?

Regards,
Jamie.

**Comment by kwm14** [comment]
@barrymcgee New favicon logo using the original building blocks attached.

**Updated favicon**

![favicon-16x16](https://cloud.githubusercontent.com/assets/17748020/16874931/44834c0c-4a94-11e6-8fc5-560442736114.png)
