### ISSUE TITLE
We need to point out to use short name to run a snap if the package name and app name are the same

### ISSUE THREAD

**Issue by liu-xiao-guo** [ubuntudesign/snapcraft.io#44]
Currently, on the http://snapcraft.io/create/ page, the very first example uses "hello" to run the example. However, for the second example, it teaches developers to use "hello-debug.hello" to run the example. A developer could be confused by the two ways of running an snap app. Why can't the first example use "hello.hello" to run the example instead of using the short form "hello"?

Thanks & best regards,
XiaoGuo

**Comment by caldav** [comment]
Closing this bug as it's not relevant anymore: command names are going to get overhauled with the introduction of snap aliases and will require a dedicated page on the topic.
