### ISSUE TITLE
Add colours to meta/snap.yaml code snipet

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/snapcraft.io#57]
In the code snipet below, add colours to font as per copy doc:

$ cat meta/snap.yaml
name: hello-world
version: 6.1
architectures: [ all ]
summary: "The 'hello-world' of snaps"
description: |
    This is a simple snap example that includes a few interesting binaries
    to demonstrate snaps and their confinement.
    * hello-world.env  - dump the env of commands run inside app sandbox
    * hello-world.evil - show how snappy sandboxes binaries
    * hello-world.sh   - enter interactive shell that runs in app sandbox
    * hello-world      - simply output text
apps:
 env:
   command: bin/env
 evil:
   command: bin/evil
 sh:
   command: bin/sh
 hello-world:
   command: bin/echo

**Comment by barrymcgee** [comment]
This is not a trivial task - currently all code styling is uniform and syntax is not highlighted. Given most developers set up their own terminal color schemes/themes, how useful is this?

**Comment by magdalena-mirowicz** [comment]
@carlaberkers we probably need to come up with some alternative

**Comment by carlaberkers** [comment]
@barrymcgee can you comment this on the copy doc? for now please remove the text in brackets  "(colour added for emphasis)" so we can go live without colour unless someone has serious objections.
