### ISSUE TITLE
Distributions row

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/snapcraft.io#62]
- Add opensuse instructions as per copy doc

- Debian instructions - style as on current live site + add a link

**Comment by magdalena-mirowicz** [comment]
Debian instructions are still not looking like on live site

**Comment by barrymcgee** [comment]
@magdalena-mirowicz What's correct, the live site or the copy doc?

**Comment by carlaberkers** [comment]
@barrymcgee let's follow the copy doc, we can leave as is for now
