### ISSUE TITLE
/community - links missing

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/snapcraft.io#72]
- Enter the snappy playpen missing github and gitter links

- join the mailing list missing link for "snapcraft mailing list"

check copy doc for details

**Comment by barrymcgee** [comment]
I did add these.. where the hell did they go.. investigating..

**Comment by barrymcgee** [comment]
@magdalena-mirowicz I'm seeing these at: https://barrymcgee.github.io/snapcraft.io/community/ ?

**Comment by magdalena-mirowicz** [comment]
@barrymcgee I can't see the links in the copy below heading there
