### ISSUE TITLE
change heading on hello world section

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#73]
please change  “hello” world tour to  “hello world" tour as per copy doc.

**Comment by barrymcgee** [comment]
@carlaberkers Where is this? On the index page? I think I changed this yesterday.. can't find any other instances of "hello"..

**Comment by barrymcgee** [comment]
https://www.dropbox.com/s/0f2j6zp7p3a37t9/Screenshot%202016-07-15%2012.21.56.png?dl=0

**Comment by magdalena-mirowicz** [comment]
@carlaberkers @barrymcgee I think it's correct already. It was only not correct in copy doc
