### ISSUE TITLE
[docs] pages missing on staging site

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/snapcraft.io#89]
snappy docs pages on http://staging.snapcraft.io/ are different from the docs pages on http://ubuntudesign.github.io/docs-demo/snappy-dev/interfaces_list/

(parts, apps as a service, debugging, publish, advanced user, etc)

is this correct?

**Comment by caldav** [comment]
The docs on the demo site are far from being finished and finished ones have been written in the context of a future new dev.ubuntu.com, not a distro-agnostic snapcraft.io, with some of the content still referring to the Snappy 15.04 manual. 

Hence, for snapcraft.io we had to use and tweak what we could from the demo site, from snapcraft/snapd in-branch doc and create from scratch what was absolutely needed. Here is the [diff](https://github.com/CanonicalLtd/snappy-docs/pull/2/files).
