### ISSUE TITLE
Missing "Launchpad ID" context in "The 'hello' world tour"

### ISSUE THREAD

**Issue by kaxing** [ubuntudesign/snapcraft.io#9]
Went through the tutorial, but I think there should be some more information for "Log in to the global snap store", since it requires **Launchpad ID** and not every audiences from cross-distros are having Ubuntu account.

**Comment by anthonydillon** [comment]
Thank you very much @kaxing.

@evandandrea could you suggest an update to the copy doc or ask the right person to update the copy doc for this issue please?

**Comment by jamiedbennett** [comment]
We are using sudo throughout the tour, can you tell us where store log in is necessary?

**Comment by barrymcgee** [comment]
@kaxing Can you address the question above please and we'll try to get this issue resolved asap? :)

**Comment by barrymcgee** [comment]
Can anyone confirm the change to be made here or will I close this issue?

**Comment by kaxing** [comment]
Hey, it's not about permission in system, but in a bit earlier version of 'snap install' will ask user to login with Launchpad ID, but I just try the latest version it doesn't ask me to do so.
